### ISSUE TITLE
Cleanup entry information in UserProfile

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#393]
This is about cleaning up

```
    // TODO: we really need to clean this up and rethink what we expose where
    // but that would be a breaking change... let's aim for 0.6
    this.entriesCountProducer = new DefaultValueProducer(this.keyring.getEntries().length);
    this.entriesCount = new ValueAndUpdates(this.entriesCountProducer);
    this.entryLabelsProducer = new DefaultValueProducer(UserProfile.labels(this.keyring.getEntries()));
    this.entryLabels = new ValueAndUpdates(this.entryLabelsProducer);
    this.entryIdsProducer = new DefaultValueProducer(UserProfile.ids(this.keyring.getEntries()));
    this.entryIds = new ValueAndUpdates(this.entryIdsProducer);
```

From the caller's perspective we have right now the data (simplified, yaml style):

```yaml
- entriesCount: 3
- entryLabels:
  - "first address"
  - undefined
  - "Savings for bad times"
- entryIds:
  - "ohb9Eufedoo7"
  - "iR4kei9ooF6g"
  - "aoki6Aeph2se"
```

all those three properties can (and must) be queried explicitly and adding an entry emits 3 different events (count updated, labels updated, ids updated) with inconsistent data between those 3 events (e.g. count becomes 4 but the 4th entry label not yet available).

To simplify this, I propose the following structure

```yaml
- entries:
  - label: "first address"
    id: "ohb9Eufedoo7"
  - label: undefined
    id: "iR4kei9ooF6g"
  - label: "Savings for bad times"
    id: "aoki6Aeph2se"
```

This gives us an interface, where the individual entries are represented as an immutable interface like

```ts
interface EntryInfo {
    readonly id: KeyringEntryId;
    readonly label: string | undefined;
}
```

and count is taken from the length of the entries array.
